apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ms-template.name" . }}
  labels:
    {{- include "ms-template.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ms-template.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ms-template.name" . }}